# Generated by Django 5.1.4 on 2025-02-22 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='get_user', to='base.staff'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='images',
            field=models.ManyToManyField(related_name='staff_images_set', to='base.image'),
        ),
    ]
