# Generated by Django 5.1.6 on 2025-02-23 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_staff_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_set', to='base.school'),
        ),
    ]
