# Generated by Django 5.1.6 on 2025-02-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_product_branchproduct_product_unique_product_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='branchproduct',
            constraint=models.UniqueConstraint(fields=('product', 'branch'), name='unique_branch_product'),
        ),
    ]
