# Generated by Django 5.1.6 on 2025-02-25 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_branchproduct_unique_branch_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('measure_unit', models.CharField(max_length=30)),
                ('consumption', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, unique=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='branchproduct',
            name='unique_branch_product',
        ),
        migrations.AlterField(
            model_name='branchproduct',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_set', to='base.branch'),
        ),
        migrations.AlterField(
            model_name='branchproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branch_products_set', to='base.product'),
        ),
        migrations.AddConstraint(
            model_name='branchproduct',
            constraint=models.UniqueConstraint(fields=('product', 'branch'), name='unique_branch_products'),
        ),
        migrations.AddField(
            model_name='branchmaterial',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials_set', to='base.branch'),
        ),
        migrations.AddField(
            model_name='branchmaterial',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_branch_materials_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='branchmaterial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branch_materials_set', to='base.material'),
        ),
        migrations.AddConstraint(
            model_name='branchmaterial',
            constraint=models.UniqueConstraint(fields=('material', 'branch'), name='unique_branch_materials'),
        ),
    ]
