# Generated by Django 5.1.6 on 2025-02-25 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_branchmaterial_material_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branchmaterial',
            name='measure_unit',
        ),
        migrations.AddField(
            model_name='material',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='2025-02-25T07:41:52.237951+02:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='created_materials_set', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='measure_unit',
            field=models.CharField(default='kilo', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
