# Generated by Django 5.1.6 on 2025-02-26 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_branchmaterial_consumption_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branchmaterial',
            name='quantity',
        ),
        migrations.AddField(
            model_name='branchmaterial',
            name='available_units',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=14),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='branchproductmaterial',
            constraint=models.UniqueConstraint(fields=('product', 'material'), name='unique_branch_product_material'),
        ),
    ]
