# Generated by Django 5.1.6 on 2025-02-27 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_branchmaterial_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('instapay', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('visa', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('hour_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('half_hour_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('time_price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('is_active', models.BooleanField(default=True)),
                ('spent_time', models.IntegerField(default=0)),
                ('finished', models.DateTimeField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills_set', to='base.branch')),
                ('children', models.ManyToManyField(related_name='child_bills_set', to='base.child')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_bills_set', to=settings.AUTH_USER_MODEL)),
                ('finished_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finished_bills_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.PositiveIntegerField(editable=False)),
                ('table_number', models.IntegerField()),
                ('take_away', models.BooleanField()),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_bills_set', to='base.bill')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_product_bills_set', to=settings.AUTH_USER_MODEL)),
                ('products', models.ManyToManyField(related_name='bills_set', to='base.branchproduct')),
                ('returned_products', models.ManyToManyField(related_name='returned_product_bills_set', to='base.branchproduct')),
            ],
        ),
    ]
