# Generated by Django 5.1.6 on 2025-02-28 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_bill_productbill'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBillProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qunatity', models.IntegerField()),
                ('notes', models.CharField(max_length=75, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductBillReturnedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qunatity', models.IntegerField()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='product',
            name='unique_product_name',
        ),
        migrations.RenameField(
            model_name='child',
            old_name='presence',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='productbill',
            name='products',
        ),
        migrations.RemoveField(
            model_name='productbill',
            name='returned_products',
        ),
        migrations.AddField(
            model_name='bill',
            name='products_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('layer2', 'layer3'), name='unique_product_name'),
        ),
        migrations.AddField(
            model_name='productbillproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.branchproduct'),
        ),
        migrations.AddField(
            model_name='productbillproduct',
            name='product_bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_set', to='base.productbill'),
        ),
        migrations.AddField(
            model_name='productbillreturnedproduct',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_product_bill_returned_products_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productbillreturnedproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.branchproduct'),
        ),
        migrations.AddField(
            model_name='productbillreturnedproduct',
            name='product_bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returned_products_set', to='base.productbill'),
        ),
    ]
