# Generated by Django 5.1.6 on 2025-02-28 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_productbillproduct_productbillreturnedproduct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='finished_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finished_bills_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
