# Generated by Django 5.1.6 on 2025-03-01 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_rename_qunatity_productbillproduct_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branch_bills_set', to='base.branch'),
        ),
    ]
