# Generated by Django 5.1.6 on 2025-03-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_bill_total_price_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='branches',
            field=models.ManyToManyField(related_name='branch_discounts_set', to='base.branch'),
        ),
        migrations.AddField(
            model_name='discount',
            name='expire_date',
            field=models.DateField(default='2024-5-30'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='type',
            field=models.CharField(max_length=20),
        ),
    ]
