# Generated by Django 5.1.6 on 2025-03-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_discount_branches_discount_expire_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='expire_date',
            field=models.DateField(default='2024-5-30', null=True),
        ),
    ]
