# Generated by Django 5.1.6 on 2025-03-06 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_discount_expire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='discount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discount_bills_set', to='base.discount'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='value',
            field=models.DecimalField(decimal_places=4, max_digits=4),
        ),
    ]
