# Generated by Django 5.1.6 on 2025-03-07 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_bill_discount_alter_discount_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='discount',
        ),
        migrations.AddField(
            model_name='bill',
            name='discount_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='discount_value',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='discount',
            name='value',
            field=models.DecimalField(decimal_places=4, max_digits=5),
        ),
    ]
