# Generated by Django 5.1.6 on 2025-03-09 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_stafffine_reason_alter_stafffine_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='vacation_days',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='StaffSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('over_time', models.IntegerField()),
                ('minus_time', models.IntegerField()),
                ('delay_time', models.IntegerField()),
                ('worked_days', models.IntegerField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_salaries_set', to='base.branch')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries_set', to='base.staff')),
            ],
        ),
    ]
