# Generated by Django 5.1.6 on 2025-03-10 16:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_staff_vacation_days_staffsalary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='vacation_days',
            new_name='allowed_absence_days',
        ),
        migrations.RenameField(
            model_name='staffsalary',
            old_name='worked_days',
            new_name='absence_days',
        ),
        migrations.AddField(
            model_name='branch',
            name='delay_allowed_time',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='delay_fine_interval',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='delay_fine_value',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='shift_hours',
            field=models.DecimalField(decimal_places=1, default=5, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffsalary',
            name='bonus_value',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffsalary',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffsalary',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='created_salaries_set', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffsalary',
            name='original_salary_value',
            field=models.DecimalField(decimal_places=2, default=3000, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffsalary',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='staffwithdraw',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdraws_set', to='base.staff'),
        ),
    ]
