# Generated by Django 5.1.6 on 2025-03-11 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_rename_vacation_days_staff_allowed_absence_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffsalary',
            name='allowed_absence_days',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffsalary',
            name='delay_allowed_time',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffsalary',
            name='delay_fine_interval',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffsalary',
            name='delay_fine_value',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffsalary',
            name='shift_hours',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
