# Generated by Django 5.1.6 on 2025-03-11 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_staffsalary_allowed_absence_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('duration', models.IntegerField()),
                ('expire_date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('branches', models.ManyToManyField(related_name='branch_subscriptions_set', to='base.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_subscriptions_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
