# Generated by Django 5.1.6 on 2025-03-14 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_subscriptioninstance_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscription_bills_set', to='base.subscription'),
        ),
    ]
