# Generated by Django 5.1.6 on 2025-03-14 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_alter_bill_subscription'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbillproduct',
            name='product_bill',
        ),
        migrations.AddField(
            model_name='productbill',
            name='products',
            field=models.ManyToManyField(to='base.productbillproduct'),
        ),
        migrations.AddField(
            model_name='productbill',
            name='returned_products',
            field=models.ManyToManyField(to='base.productbillreturnedproduct'),
        ),
        migrations.AddField(
            model_name='productbillproduct',
            name='product_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products_set', to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productbillreturnedproduct',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_returned_products_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_offers_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BranchOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('sold_units', models.IntegerField()),
                ('expire_date', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers_set', to='base.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_branch_offers_set', to=settings.AUTH_USER_MODEL)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branch_offers_set', to='base.offer')),
            ],
        ),
        migrations.CreateModel(
            name='BranchOfferProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_set', to='base.branchoffer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_products_set', to='base.branchproduct')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('offer', 'product'), name='unique_branch_offer_product')],
            },
        ),
        migrations.AddConstraint(
            model_name='branchoffer',
            constraint=models.UniqueConstraint(fields=('offer', 'branch'), name='unique_branch_offer'),
        ),
    ]
