# Generated by Django 5.1.6 on 2025-03-14 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_alter_branchoffer_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchoffer',
            name='sold_units',
            field=models.IntegerField(default=0),
        ),
    ]
