# Generated by Django 5.0.7 on 2025-04-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_bill_children_count_staffsalary_total_value_cashier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffsalary',
            name='total_value',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
