# Generated by Django 5.2.3 on 2025-07-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_alter_staffsalary_total_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Cashier',
        ),
    ]
