# Generated by Django 5.2.3 on 2025-08-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_alter_child_address_delete_cashier'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='is_allowed_age',
            field=models.BooleanField(default=False),
        ),
    ]
