# Generated by Django 5.2.3 on 2025-08-09 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_bill_is_allowed_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='layer1',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='layer2',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AddIndex(
            model_name='branchproduct',
            index=models.Index(fields=['branch', 'product'], name='base_branch_branch__874af0_idx'),
        ),
    ]
