# Generated by Django 5.2.3 on 2025-08-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_alter_product_layer1_alter_product_layer2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='is_allowed_age',
            field=models.BooleanField(default=True),
        ),
    ]
