# Generated by Django 5.2.3 on 2025-08-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_alter_bill_is_allowed_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='discount_value',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
