# Generated by Django 5.2.3 on 2025-08-29 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_alter_bill_discount_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='discount_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bill',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscription_bills_set', to='base.subscription'),
        ),
    ]
