# Generated by Django 5.2.3 on 2025-09-27 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0048_branchofferproduct_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discount_bills_set', to='base.discount'),
        ),
    ]
