# Generated by Django 5.2.3 on 2025-09-27 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0049_bill_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='calculations_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calculations_updated_bills_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bill',
            name='is_calculations_updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bill',
            name='finished_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finished_bills_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
