# Generated by Django 5.2.3 on 2025-10-31 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0050_bill_calculations_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
