# Generated by Django 5.2.3 on 2026-02-27 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0051_child_is_blocked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptioninstance',
            name='hours',
        ),
        migrations.AddField(
            model_name='subscriptioninstance',
            name='base_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='subscriptioninstance',
            name='remaining_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
