# Generated by Django 5.2.3 on 2026-02-27 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0052_remove_subscriptioninstance_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscription_bills_set', to='base.subscriptioninstance'),
        ),
    ]
