# Generated by Django 5.2.3 on 2026-03-14 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0053_alter_bill_subscription'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductBill',
            new_name='CafeBill',
        ),
        migrations.RenameModel(
            old_name='ProductBillProduct',
            new_name='CafeBillProduct',
        ),
        migrations.RenameModel(
            old_name='ProductBillReturnedProduct',
            new_name='CafeBillReturnedProduct',
        ),
        migrations.RemoveField(
            model_name='branchmaterial',
            name='available_units',
        ),
        migrations.RemoveField(
            model_name='material',
            name='measure_unit',
        ),
        migrations.AddField(
            model_name='branchmaterial',
            name='warning_units',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CafeProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('image', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_product_categories_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('transaction_type', models.CharField(choices=[('stock_out', 'stock_out'), ('stock_in', 'stock_in')], max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_transactions_set', to='base.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_material_transactions_set', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_set', to='base.material')),
            ],
        ),
    ]
