# Generated by Django 5.2.3 on 2026-06-19 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0054_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='notes',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
