# Generated by Django 5.2.3 on 2026-03-16 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0055_material_type_cafeproduct_branchcafeproduct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafebill',
            name='products',
        ),
        migrations.RemoveField(
            model_name='cafebillreturnedproduct',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='cafebillreturnedproduct',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='cafebill',
            name='returned_products',
        ),
        migrations.RenameField(
            model_name='materialtransaction',
            old_name='qty',
            new_name='quantity',
        ),
        migrations.CreateModel(
            name='CafeBillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_product_id', models.PositiveIntegerField()),
                ('quantity', models.IntegerField()),
                ('notes', models.CharField(max_length=75, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('branch_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cafe_bills_items_set', to='base.branchcafeproduct')),
            ],
        ),
        migrations.AddField(
            model_name='cafebill',
            name='items',
            field=models.ManyToManyField(to='base.cafebillitem'),
        ),
        migrations.CreateModel(
            name='CafeBillReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_product_id', models.PositiveIntegerField()),
                ('quantity', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('branch_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cafe_bills_returns_set', to='base.branchcafeproduct')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_product_bill_returned_products_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cafebill',
            name='returns',
            field=models.ManyToManyField(to='base.cafebillreturn'),
        ),
        migrations.DeleteModel(
            name='CafeBillProduct',
        ),
        migrations.DeleteModel(
            name='CafeBillReturnedProduct',
        ),
    ]
