# Generated by Django 4.2.29 on 2026-06-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0055_bill_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='serial',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
