# Generated by Django 5.2.3 on 2026-07-18 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0056_bill_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='notes_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notes_updated_bills_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
