# Generated by Django 5.2.3 on 2026-03-18 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0059_remove_m2m_make_fk_required'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CafeProductSauces',
            new_name='CafeProductSauce',
        ),
        migrations.RemoveField(
            model_name='cafebillitem',
            name='old_product_id',
        ),
        migrations.RemoveField(
            model_name='cafebillreturn',
            name='old_product_id',
        ),
        migrations.AddField(
            model_name='cafebillitem',
            name='add_ons',
            field=models.ManyToManyField(to='base.cafeproductaddon'),
        ),
        migrations.AddField(
            model_name='cafebillitem',
            name='old_branch_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cafe_bills_old_products_set', to='base.branchproduct'),
        ),
        migrations.AddField(
            model_name='cafebillitem',
            name='sauces',
            field=models.ManyToManyField(to='base.cafeproductsauce'),
        ),
        migrations.AddField(
            model_name='cafebillreturn',
            name='old_branch_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cafe_bills_old_returned_products_set', to='base.branchproduct'),
        ),
    ]
