# Generated by Django 5.2.3 on 2026-08-07 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0059_billtimepause'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=500)),
                ('method', models.CharField(max_length=10)),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('raw_body', models.TextField(blank=True, default='')),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('query_params', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_valid', models.BooleanField(default=False)),
                ('response_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('processing_result', models.JSONField(blank=True, default=dict)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        )
    ]
