# Generated by Django 5.2.3 on 2026-08-07 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0060_webhookcall_outboundmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS')], default='whatsapp', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed'), ('deleted', 'Deleted')], default='pending', max_length=20)),
                ('provider_message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('logs', models.JSONField(blank=True, default=list)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_messages', to='base.bill')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_outbound_messages', to='base.child')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_outbound_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'outbound_messages',
                'constraints': [models.UniqueConstraint(fields=('channel', 'phone_number', 'bill'), name='unique_outbound_message_per_bill_phone_channel')],
            },
        ),
    ]
