# Generated by Django 5.2.3 on 2026-03-18 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0060_rename_cafeproductsauces_cafeproductsauce_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CafeProductAddOn',
            new_name='CafeProductAddOns',
        ),
        migrations.RenameModel(
            old_name='CafeProductSauce',
            new_name='CafeProductSauces',
        ),
    ]
