# Generated by Django 5.2.3 on 2026-03-19 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0060_alter_product_name_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='layer2',
            field=models.CharField(max_length=150),
        ),
    ]
