# Generated by Django 5.2.3 on 2026-03-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0061_alter_product_layer2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='layer1',
            field=models.CharField(max_length=150),
        ),
    ]
