# Generated by Django 5.2.3 on 2026-03-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0062_alter_product_layer1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='measure_unit',
            field=models.CharField(default='مللي/جرام', max_length=30),
        ),
    ]
