# Generated by Django 5.2.3 on 2026-03-19 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0063_alter_material_measure_unit'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='unique_product_name',
        ),
    ]
