# Generated by Django 5.2.3 on 2026-03-21 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0064_remove_product_unique_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbill',
            name='notes',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='productbillproduct',
            name='branch_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productbill_products_set', to='base.branchproduct'),
        ),
        migrations.AddField(
            model_name='productbillproduct',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, null = True, blank=True, max_digits=10),
        ),
        migrations.AddField(
            model_name='productbillreturnedproduct',
            name='branch_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productbill_returned_products_set', to='base.branchproduct'),
        ),
        migrations.AddField(
            model_name='productbillreturnedproduct',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, null = True, blank=True, max_digits=10),
        ),
    ]
