# Generated by Django 5.2.3 on 2026-03-21 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0066_sql_map_productbill_branch_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbillproduct',
            name='branch_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productbill_products_set', to='base.branchproduct'),
        ),
        migrations.AlterField(
            model_name='productbillreturnedproduct',
            name='branch_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productbill_returned_products_set', to='base.branchproduct'),
        ),
    ]
