# Generated by Django 5.2.3 on 2026-03-22 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0067_alter_productbillproduct_branch_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='productsauces',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='productsauces',
            name='material',
        ),
        migrations.RemoveField(
            model_name='productsauces',
            name='product',
        ),
        migrations.RemoveField(
            model_name='materialtransaction',
            name='material',
        ),
        migrations.AddField(
            model_name='materialtransaction',
            name='branch_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_set', to='base.branchmaterial'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productbillproduct',
            name='add_ons',
            field=models.ManyToManyField(to='base.productaddons'),
        ),
        migrations.AddField(
            model_name='productbillreturnedproduct',
            name='add_ons',
            field=models.ManyToManyField(to='base.productaddons'),
        ),
        migrations.AddConstraint(
            model_name='productreciepe',
            constraint=models.UniqueConstraint(fields=('product', 'material'), name='unique_product_material_reciepe'),
        ),
        migrations.AddField(
            model_name='productoptions',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_cafe_product_sauces_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productoptions',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cafe_product_sauces_set', to='base.material'),
        ),
        migrations.AddField(
            model_name='productoptions',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sauces_set', to='base.product'),
        ),
        migrations.AddField(
            model_name='productbillproduct',
            name='options',
            field=models.ManyToManyField(to='base.productoptions'),
        ),
        migrations.AddField(
            model_name='productbillreturnedproduct',
            name='options',
            field=models.ManyToManyField(to='base.productoptions'),
        ),
        migrations.DeleteModel(
            name='ProductSauces',
        ),
        migrations.AddConstraint(
            model_name='productoptions',
            constraint=models.UniqueConstraint(fields=('product', 'material'), name='unique_product_material_option'),
        ),
    ]
