# Generated by Django 5.2.3 on 2026-03-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0068_materialtransaction_branch_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productoptions',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
