# Generated by Django 5.2.3 on 2026-03-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0069_alter_productcategory_image_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchmaterial',
            name='available_units',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='productaddons',
            name='consumption',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productoptions',
            name='consumption',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productreciepe',
            name='consumption',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='materialtransaction',
            index=models.Index(fields=['branch_material', 'transaction_type', 'created'], name='base_materi_branch__50dbf5_idx'),
        ),
    ]
